name: tlu_attendance
environment:
  sdk: '>=3.5.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_web_plugins:
    sdk: flutter   # <--- thêm dòng này

  go_router: ^14.2.7
  flutter_riverpod: ^2.5.1
  dio: ^5.7.0
  flutter_secure_storage: ^9.2.2
  flutter_dotenv: ^5.1.0
  mobile_scanner: ^5.2.3
  camera: ^0.10.6
  intl: ^0.19.0
  permission_handler: ^11.3.1
  flutter_svg: ^2.0.10+1
  file_picker: ^8.1.2
  path_provider: ^2.1.4
  open_filex: ^4.4.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  assets:
    - .env
    - assets/images/logo_tlu.png
