version: "3.9"

services:
  face_api:
    build:
      context: ../ai_service
    container_name: face_api
    environment:
      - FACE_MODEL_NAME=buffalo_l
      - FACE_DET_SIZE=320
      - FACE_PROVIDERS=CPUExecutionProvider
    volumes:
      - face_models:/root/.insightface
    ports:
      - "8001:8000"
    healthcheck:
      test: ["CMD", "wget", "-qO-", "http://127.0.0.1:8000/health"]
      interval: 10s
      timeout: 5s
      retries: 10

  mysql:
    image: mysql:8.0
    container_name: mysql
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: attendance
      MYSQL_USER: attendance
      MYSQL_PASSWORD: attendance
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "127.0.0.1", "-uroot", "-proot"]
      interval: 5s
      timeout: 5s
      retries: 20

  backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: laravel_backend
    depends_on:
      mysql:
        condition: service_healthy
      face_api:
        condition: service_healthy
    environment:
      WEB_DOCUMENT_ROOT: /app/public
      APP_ENV: ${APP_ENV}
      APP_DEBUG: ${APP_DEBUG}
      APP_URL: ${APP_URL}
      APP_TIMEZONE: ${APP_TIMEZONE:-Asia/Ho_Chi_Minh}
      DB_CONNECTION: mysql
      DB_HOST: mysql
      DB_PORT: 3306
      DB_DATABASE: attendance
      DB_USERNAME: attendance
      DB_PASSWORD: attendance
      FACE_PROVIDER: http
      FACE_API_BASE: http://face_api:8000
    working_dir: /app
    volumes:
      - ./:/app
      - vendor_data:/app/vendor
      - cache_data:/app/bootstrap/cache
      - storage_data:/app/storage
    ports:
      - "8080:80"
    user: "www-data:www-data"
    restart: unless-stopped

volumes:
  db_data:
  face_models:
  vendor_data:
  cache_data:
  storage_data:
