version: "3.9"

services:
  mysql:
    image: mysql:8.0
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: attendance
      MYSQL_USER: attendance
      MYSQL_PASSWORD: attendance
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "127.0.0.1", "-uroot", "-proot"]
      interval: 5s
      timeout: 5s
      retries: 20

  app:
    image: webdevops/php-nginx:8.3
    depends_on:
      mysql:
        condition: service_healthy
    environment:
      WEB_DOCUMENT_ROOT: /app/public
      APP_ENV: ${APP_ENV}
      APP_DEBUG: ${APP_DEBUG}
      APP_URL: ${APP_URL}
      APP_TIMEZONE: ${APP_TIMEZONE}
      DB_CONNECTION: mysql
      DB_HOST: mysql
      DB_PORT: 3306
      DB_DATABASE: attendance
      DB_USERNAME: attendance
      DB_PASSWORD: attendance
    working_dir: /app
    volumes:
      - ./:/app
    ports:
      - "8080:80"
    command: >
      sh -lc "\
        composer install --no-interaction --prefer-dist && \
        if [ -z \"$(grep ^APP_KEY= .env | cut -d= -f2)\" ]; then php artisan key:generate --force; else echo 'APP_KEY exists'; fi && \
        php artisan migrate --force && \
        php artisan db:seed --force && \
        supervisord -n"

volumes:
  db_data:
